function aesthetic() {
  document.getElementById('shot1').src = 'image/shirtxl1.jpeg';
  document.getElementById('shot2').src = 'image/shirtxl2.jpg';
  document.getElementById('shot3').src = 'image/shirtxl3.jpeg';
  document.getElementById('shot4').src = 'image/shirtxl4.jpeg';
  document.getElementById('shot5').src = 'image/shirtxl5.jpg';
  document.getElementById('shot6').src = 'image/shirtxl6.jpeg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Black Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name3').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name4').innerHTML='Cotton Oversize Naruto';
  document.getElementById('Name5').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name6').innerHTML='Cotton Oversize Kamekazee';
  document.getElementById('value1').innerHTML='₱ 450.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="C:\Users\irish\OneDrive\文档\Downloads\Emskirt Clothing Line(Kyle Mizon) (1)\My-Product\Buying - Copy.html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML='₱ 450.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="My-Product/Buying 1.html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML='₱ 450.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="My-Product/Buying 2.html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML='₱ 450.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="My-Product/Buying 3.html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML='₱ 450.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="My-Product/Buying 4.html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML='₱ 450.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="My-Product/Buying 5.html"><button class="buy6">Buy Now!</button></a>';
}
function couple() {
  document.getElementById('shot1').src='image/couple1.jpeg';
  document.getElementById('shot2').src='image/couple2.jpg';
  document.getElementById('shot3').src='image/couple3.jpg';
  document.getElementById('shot4').src='image/coulple4.jpg';
  document.getElementById('shot5').src='image/couple5.jpg';
  document.getElementById('shot6').src='image/couple6.jpg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Couple  Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('value1').innerHTML = '₱ 280.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(6).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 280.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(7).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 280.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(8).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 280.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(9).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 280.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(10).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 280.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(11).html"><button class="buy6">Buy Now!</button></a>';
}
function Doodle() {
  document.getElementById('shot1').src = 'image/doodle1.jpeg';
  document.getElementById('shot2').src = 'image/doodle2.jpeg';
  document.getElementById('shot3').src = 'image/doodle3.jpeg';
  document.getElementById('shot4').src = 'image/doodle4.jpeg';
  document.getElementById('shot5').src = 'image/doodle5.jpg';
  document.getElementById('shot6').src = 'image/doodle6.jpg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('value1').innerHTML = '₱ 350.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(12).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 350.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(13).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 350.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(14).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 350.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(15).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 350.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(16).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 350.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(17).html"><button class="buy6">Buy Now!</button></a>';
}
function Plain() {
  document.getElementById('shot1').src = 'image/plain1.jpeg';
  document.getElementById('shot2').src = 'image/plain2.jpeg';
  document.getElementById('shot3').src = 'image/plain3.jpeg';
  document.getElementById('shot4').src = 'image/plain4.jpeg';
  document.getElementById('shot5').src = 'image/plain5.jpeg';
  document.getElementById('shot6').src = 'image/plain6.jpeg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Pink Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Black Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Gray Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Mint Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Green Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize LightBrown Shirt';
  document.getElementById('value1').innerHTML = '₱ 180.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(18).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 180.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(19).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 180.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(20).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 180.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(21).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 180.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(22).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 180.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="file:///C:/Users/irish/OneDrive/%E6%96%87%E6%A1%A3/Downloads/Emskirt%20Clothing%20Line(Kyle%20Mizon)%20(1)/My-Product/Buying%20-%20Copy%20(23).html"><button class="buy6">Buy Now!</button></a>';
}